# -----------------------------
# CICFlowMeter -> Model feature mapping
# -----------------------------

CIC_TO_MODEL_MAP = {
    'Dst Port': 'DestinationPort',
    'Flow Duration': 'FlowDuration',
    'Total Fwd Packet': 'TotalFwdPackets',
    'Total Bwd packets': 'TotalBackwardPackets',
    'Total Length of Fwd Packet': 'TotalLengthofFwdPackets',
    'Total Length of Bwd Packet': 'TotalLengthofBwdPackets',
    'Fwd Packet Length Max': 'FwdPacketLengthMax',
    'Fwd Packet Length Min': 'FwdPacketLengthMin',
    'Fwd Packet Length Mean': 'FwdPacketLengthMean',
    'Fwd Packet Length Std': 'FwdPacketLengthStd',
    'Bwd Packet Length Max': 'BwdPacketLengthMax',
    'Bwd Packet Length Min': 'BwdPacketLengthMin',
    'Bwd Packet Length Mean': 'BwdPacketLengthMean',
    'Bwd Packet Length Std': 'BwdPacketLengthStd',
    'Flow Bytes/s': 'FlowBytess',
    'Flow Packets/s': 'FlowPacketss',
    'Flow IAT Mean': 'FlowIATMean',
    'Flow IAT Std': 'FlowIATStd',
    'Flow IAT Max': 'FlowIATMax',
    'Flow IAT Min': 'FlowIATMin',
    'Fwd IAT Total': 'FwdIATTotal',
    'Fwd IAT Mean': 'FwdIATMean',
    'Fwd IAT Std': 'FwdIATStd',
    'Fwd IAT Max': 'FwdIATMax',
    'Fwd IAT Min': 'FwdIATMin',
    'Bwd IAT Total': 'BwdIATTotal',
    'Bwd IAT Mean': 'BwdIATMean',
    'Bwd IAT Std': 'BwdIATStd',
    'Bwd IAT Max': 'BwdIATMax',
    'Bwd IAT Min': 'BwdIATMin',
    'Fwd PSH Flags': 'FwdPSHFlags',
    'Bwd PSH Flags': 'BwdPSHFlags',
    'Fwd URG Flags': 'FwdURGFlags',
    'Bwd URG Flags': 'BwdURGFlags',
    'Fwd Header Length': 'FwdHeaderLength',
    'Bwd Header Length': 'BwdHeaderLength',
    'Fwd Packets/s': 'FwdPacketss',
    'Bwd Packets/s': 'BwdPacketss',
    'Packet Length Min': 'MinPacketLength',
    'Packet Length Max': 'MaxPacketLength',
    'Packet Length Mean': 'PacketLengthMean',
    'Packet Length Std': 'PacketLengthStd',
    'Packet Length Variance': 'PacketLengthVariance',
    'FIN Flag Count': 'FINFlagCount',
    'SYN Flag Count': 'SYNFlagCount',
    'RST Flag Count': 'RSTFlagCount',
    'PSH Flag Count': 'PSHFlagCount',
    'ACK Flag Count': 'ACKFlagCount',
    'URG Flag Count': 'URGFlagCount',
    'CWR Flag Count': 'CWEFlagCount',   # bewusst so gemappt
    'ECE Flag Count': 'ECEFlagCount',
    'Down/Up Ratio': 'DownUpRatio',
    'Average Packet Size': 'AveragePacketSize',
    'Fwd Segment Size Avg': 'AvgFwdSegmentSize',
    'Bwd Segment Size Avg': 'AvgBwdSegmentSize',
    'Fwd Bytes/Bulk Avg': 'FwdAvgBytesBulk',
    'Fwd Packet/Bulk Avg': 'FwdAvgPacketsBulk',
    'Fwd Bulk Rate Avg': 'FwdAvgBulkRate',
    'Bwd Bytes/Bulk Avg': 'BwdAvgBytesBulk',
    'Bwd Packet/Bulk Avg': 'BwdAvgPacketsBulk',
    'Bwd Bulk Rate Avg': 'BwdAvgBulkRate',
    'Subflow Fwd Packets': 'SubflowFwdPackets',
    'Subflow Fwd Bytes': 'SubflowFwdBytes',
    'Subflow Bwd Packets': 'SubflowBwdPackets',
    'Subflow Bwd Bytes': 'SubflowBwdBytes',
    'FWD Init Win Bytes': 'Init_Win_bytes_forward',
    'Bwd Init Win Bytes': 'Init_Win_bytes_backward',
    'Fwd Act Data Pkts': 'act_data_pkt_fwd',
    'Fwd Seg Size Min': 'min_seg_size_forward',
    'Active Mean': 'ActiveMean',
    'Active Std': 'ActiveStd',
    'Active Max': 'ActiveMax',
    'Active Min': 'ActiveMin',
    'Idle Mean': 'IdleMean',
    'Idle Std': 'IdleStd',
    'Idle Max': 'IdleMax',
    'Idle Min': 'IdleMin',
    'Label': 'Label',
}